export const componentGroups = [
  {
    name: "作業面と移動",
    ids: [
      "app-shell",
      "command-menu",
      "split-view",
      "section",
      "surface",
      "context-bar",
      "page-header",
      "breadcrumb",
      "navigation",
      "tabs",
      "pagination",
      "steps",
      "divider",
    ],
  },
  {
    name: "入力と選択",
    ids: [
      "field",
      "field-group",
      "input-group",
      "switch",
      "range",
      "suggestion",
      "date-picker",
      "file-input",
      "filter-bar",
    ],
  },
  {
    name: "操作と補足",
    ids: [
      "button",
      "toolbar",
      "dropdown-menu",
      "dialog",
      "popover",
      "disclosure",
      "danger-zone",
      "keycap",
    ],
  },
  {
    name: "内容と一覧",
    ids: [
      "card",
      "message",
      "message-list",
      "table",
      "value-list",
      "data-list",
      "action-list",
      "file-item",
      "image-frame",
      "comparison",
      "avatar",
      "tag",
      "icon",
      "code-block",
    ],
  },
  { name: "仕事と予定", ids: ["task-list", "timeline", "calendar", "board", "statistic"] },
  {
    name: "状態と結果",
    ids: ["badge", "notice", "error-summary", "empty-state", "progress", "loading", "toast"],
  },
] as const;
